### ISSUE TITLE
Error while copying content to a stream.

### ISSUE THREAD

**Issue by SunSha** [twitchax/AspNetCore.Proxy#20]
I am making a post request, which randomly ends'up in following error: 
```
Error while copying content to a stream.

   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at AspNetCore.Proxy.Helpers.HandleProxy(HttpContext context, String uri, Func`3 onFailure).
```

It very intermittent error, sometimes it works. My usage is very simple there is post request, that I send to another service. A controller task with return this.ProxyAsync(url); Any idea what it can be ? Thanks

**Comment by twitchax** [comment]
Interesting.

Can you provide the simplest possible repro, or, better yet, a test case similar to the others that fails due to this issue?

**Comment by twitchax** [comment]
@SunSha, ping?

**Comment by twitchax** [comment]
Closing due to lack of repro.
